VideoSubscription/VideoSubscription/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from subscription import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('videos/', include('subscription.urls')),
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

VideoSubscription/subscription/urls.py
from django.urls import path
from . import views


app_name = 'subscription'

urlpatterns = [
    path('registraion', views.UserregisterView.as_view(), name='registraion'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('home', views.HomePageView.as_view(), name='home'),
    path('watch_video/<int:pk>', views.WatchVideoView.as_view(), name='watch_video'),
    path('payment', views.PaymentView.as_view(), name='payment'),
]

VideoSubscription/subscription/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
# from django.contrib.auth import get_user_model
# User = get_user_model()
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, username, password = None):
        if not email:
            raise ValueError("Enter your email.")
        if not username:
            raise ValueError("Enter your username.")

        user = self.model(
            email = self.normalize_email(email),
            username = username,
        )

        user.set_password(password)
        user.save(using = self.db)
        return user

    def create_superuser(self, email, username, password = None):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
        )

        user.is_active = True
        user.is_admin  = True
        user.is_staff  = True
        user.is_superuser = True

        user.save(using = self.db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=70, unique=True)
    first_name = models.CharField(max_length=70, blank=True)
    last_name = models.CharField(max_length=70, blank=True)
    email = models.EmailField(max_length=70, unique=True)
    phone_number = models.PositiveIntegerField(blank=True, null=True)
    FREE = 'free'
    MONTHLY = 'monthly'
    YEARLY = 'yearly'
    SUBSCRIPTION = (
        (FREE, 'Free'),
        (MONTHLY, 'Monthly'),
        (YEARLY, 'yearly')
    )
    subscribe = models.CharField(null=True, blank=True, choices=SUBSCRIPTION, max_length=7, default=FREE)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def __str__(self):
        return self.username


class Video(models.Model):
    FREE = 'free'
    MONTHLY = 'monthly'
    YEARLY = 'yearly'
    SUBSCRIPTION = (
        (FREE, 'Free'),
        (MONTHLY, 'Monthly'),
        (YEARLY, 'yearly')
    )
    name = models.CharField(max_length=50)
    discription = models.TextField()
    subscription_type = models.CharField(null=True, blank=True, choices=SUBSCRIPTION, max_length=7, default=FREE)
    image = models.ImageField(upload_to='images/', default='images/thumbnail.jpg')
    video= models.FileField(upload_to='videos/', null=True)


class Subscription(models.Model):
    FREE = "free"
    MONTHLY = "monthly"
    YEARLY = "yearly"
    MEMBERSHIP = (
        (FREE, "free"),
        (MONTHLY, "monthly"),
        (YEARLY, "yearly")
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    membership_type = models.CharField(default=FREE, choices=MEMBERSHIP, max_length=10)
    expiry_date = models.DateTimeField(null=True, blank=True)

VideoSubscription/subscription/forms.py
from django import forms
from .models import User



class AdminRegisterform(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-control w-50 m-auto'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone_number', 'password']
        widgets = {
            'username' : forms.TextInput(
                attrs={'class' : 'form-control w-50 m-auto'}
            ),             
            'first_name' : forms.TextInput(
                attrs={'class' : 'form-control w-50 m-auto'}
            ),             
            'last_name' : forms.TextInput(
                attrs={'class' : 'form-control w-50 m-auto'}
            ),             
            'email' : forms.EmailInput(
                attrs={'class' : 'form-control w-50 m-auto'}
            ),
            'phone_number' : forms.TextInput(
                attrs={'class' : 'form-control w-50 m-auto'}
            ), 
            'password' : forms.PasswordInput(
                attrs={'class' : 'form-control w-50 m-auto'}
            ),    
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.is_staff = True
        if commit:
            user.save()
        return user


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']
        widgets = {
            'email' : forms.EmailInput(
                attrs={'class' : 'form-control w-50 m-auto'}
            ),
            'password' : forms.PasswordInput(
                attrs={'class' : 'form-control w-50 m-auto'}
            )
        }

VideoSubscription/subscription/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, View
from requests import request
from .forms import AdminRegisterform, LoginForm
from .models import User, Video, Subscription
from django.contrib.auth import authenticate, login, logout
import stripe
from django.conf import settings
from datetime import datetime, timedelta
# Create your views here.

class UserregisterView(CreateView):
    model = User
    form_class = AdminRegisterform
    template_name = 'registration.html'
    success_url = 'login'


class HomePageView(ListView):
    model = Video
    template_name = 'home.html'
    context_object_name = 'videos'


class WatchVideoView(DetailView):
    model = Video
    template_name = 'watch_video.html'


class LoginView(View):
    def post(self,request):
        form = LoginForm(request.POST)
        user_name = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=user_name,password=password)
        if user is not None:
            print(user)
            # if user.is_staff == True:
            login(request, user)
            return redirect('subscription:home')
        else:
            return render(request,'login.html',{'form':form}) 

    def get(self,request):
        form = LoginForm()
        return render(request,'login.html',{'form':form})


class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect('subscription:registraion')


class PaymentView(View):
    def get(self, request):
        return render(request, 'payment.html', {'key':settings.STRIPE_PUBLIC_KEY})

    def post(self, request):
        stripe.api_key = settings.STRIPE_SECRET_KEY
        sub_type = request.POST.get('sub_type')
        customer = stripe.Customer.create(
            name = request.user,
            payment_method=request.POST.get('paymentMethodToken'),
            # source = request.POST['stripeToken']
        )
        charge = stripe.PaymentIntent.create(
            customer = customer.id,
            amount=int(sub_type)*100,
            currency='inr',
            payment_method_types=['card'],
        )
        if charge:
            user = User.objects.get(username=request.user)
            sub = Subscription.objects.create(user=request.user)
            print(user)
            if charge.amount == 2400*100:
                user.subscribe = "yearly"
                expiry = datetime.now() + timedelta(days=365)
                sub.expiry_date = expiry
                sub.membership_type = "yearly"
                user.save()
                sub.save()
            if charge.amount == 250*100:
                user.subscribe = "monthly"
                expiry = datetime.now() + timedelta(days=30)
                sub.expiry_date = expiry
                sub.membership_type = "monthly"
                user.save()
                sub.save()
        return redirect('subscription:home')

VideoSubscription/subscription/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <script defer src="{% static 'js/bootstrap.js' %}"></script>
  <script defer src="{% static 'js/jquery.js' %}"></script>
  <title>Document</title>
</head>

<body>
  <h1 class="text-center m-5">Welcom {{request.user}}</h1>
  <div class="text-center">
    <a href="{% url 'subscription:logout' %}" class="btn btn-primary">Logout</a>
  </div><br>
  <div class="form-control w-75 m-auto">
    <div class="row">
      {% for video in videos %}
      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{{video.image.url}}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{video.name}}</h5>
            <p class="card-text">{{video.discription}}</p>

            {% if video.subscription_type == "free" %}
            <p class="badge bg-success">Free</p><br>
            <a href="{% url 'subscription:watch_video' video.id %}" class="btn btn-primary">Watch Video</a>
            {% endif %}

            {% if video.subscription_type == "monthly" %}
            <p class="badge bg-success">Monthly</p><br>

            {% if request.user.subscribe == "free" %}
              <a href="{% url 'subscription:payment' %}" class="btn btn-warning">Get Subscription</a>
            {% elif request.user.subscribe == "monthly" or request.user.subscribe == "yearly" %}
              <a href="{% url 'subscription:watch_video' video.id %}" class="btn btn-primary">Watch Video</a>
            {% endif %}

            {% endif %}

            {% if video.subscription_type == "yearly" %}
            <p class="badge bg-success">Yearly</p><br>

            {% if request.user.subscribe == "free" or request.user.subscribe == "monthly" %}
              <a href="{% url 'subscription:payment' %}" class="btn btn-warning">Get Subscription</a>
            {% elif request.user.subscribe == "yearly" %}
              <a href="{% url 'subscription:watch_video' video.id %}" class="btn btn-primary">Watch Video</a>
            {% endif %}

            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</body>

</html>

VideoSubscription/subscription/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script defer src="{% static 'js/bootstrap.js' %}"></script>
    <script defer src="{% static 'js/jquery.js' %}"></script>
    <title>Document</title>
</head>
<body>
    <h1 class="text-center my-5">Login</h1>
    <form action="" method="POST" class="form-control text-center" novalidate onsubmit="return login_validate()">
        {% csrf_token %}
        <label for="">Email :</label><br><br>
        {{form.email}}
        <span id="error_email" class="text-danger"></span><br><br>
        <label for="">Password :</label><br><br>
        {{form.password}}
        <span id="error_password" class="text-danger"></span><br><br>
        <input type="submit" value="Submit" class="btn btn-success"><br><br>
        For register <a href="{% url 'subscription:registraion' %}" class="text-muted">Register</a>
    </form> 
</body>
</html>

VideoSubscription/subscription/templates/payment.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Accept a payment</title>
    <meta name="description" content="A demo of a payment on Stripe" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="https://code.jquery.com/jquery-2.0.2.min.js"></script>
    <script defer src="{% static 'js/bootstrap.js' %}"></script>
    <script defer src="{% static 'js/jquery.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'js/checkout.js' %}" defer></script>
</head>

<body>
    <div class="form-control w-75 m-auto text-center mt-5">
        <h1>Get Subscription</h1>
        <h2>Our Plans</h2>
        <h3>Monthly : 250₹</h3>
        <h3>Yearly : 2400₹</h3>

        <form action="" method="POST" id="payment-form">
            {% csrf_token %}
            <select name="sub_type" id="">
                <option value="250">Monthly - 250₹</option>
                <option value="2400">Yealry - 2400₹</option>
            </select>
            <div class="form-row">
                <label for="card-element">
                    Credit or debit card
                </label>
                <div id="card-element">
                    <!-- a Stripe Element will be inserted here. -->
                </div>

                <!-- Used to display form errors -->
                <div id="card-errors" role="alert"></div>
            </div>
            <button>Submit Payment</button>
        </form>
    </div>


    <script>
        var stripe = Stripe('pk_test_51L3uRpSBHoeSNjbt8e8HtvOpniS7qpCjvvkTmiQcNnTribAXeT8D5OaXKlTD7fjaSMrJc0sScddL9wbyMVfFDfsM00wVnDaPxW');
        var elements = stripe.elements();

        var style = {
            base: {
                color: '#303238',
                fontSize: '16px',
                fontFamily: '"Open Sans", sans-serif',
                fontSmoothing: 'antialiased',
                '::placeholder': {
                    color: '#CFD7DF',
                },
            },
            invalid: {
                color: '#e5424d',
                ':focus': {
                    color: '#303238',
                },
            },
        };
        var card = elements.create('card', { style: style });
        card.mount('#card-element');
    </script>


</body>

</html>

VideoSubscription/subscription/templates/registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script defer src="{% static 'js/bootstrap.js' %}"></script>
    <script defer src="{% static 'js/jquery.js' %}"></script>
    <title>Document</title>
</head>
<body>
    <h1 class="text-center my-5">Register</h1>
    <form action="" method="POST" class="form-control text-center" novalidate onsubmit="return validate()">
        {% csrf_token %}
        <label for="">Username :</label><br>
        {{form.username}}
        <span id="error_username" class="text-danger"></span><br>
        <label for="">First Name :</label><br>
        {{form.first_name}}
        <span id="error_f_name" class="text-danger"></span><br>
        <label for="">Last Name :</label><br>
        {{form.last_name}}
        <span id="error_l_name" class="text-danger"></span><br>
        <label for="">Email :</label><br>
        {{form.email}}
        <span id="error_email" class="text-danger"></span><br>
        <label for="">Password :</label><br>
        {{form.password}}
        <span id="error_password" class="text-danger"></span><br><br>
        <label for="">Confirm Password :</label><br>
        {{form.confirm_password}}
        <span id="error_c_password" class="text-danger"></span><br>          
        <input type="submit" value="Submit" class="btn btn-success"><br><br>
        Try to login if already registered <a href="{% url 'subscription:login' %}" class="text-muted">Log in</a>
    </form>
    
</body>
</html>

VideoSubscription/subscription/templates/watch_video.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script defer src="{% static 'js/bootstrap.js' %}"></script>
    <script defer src="{% static 'js/jquery.js' %}"></script>
    <title>Document</title>
</head>

<body>
    <video autoplay="autoplay" controls="controls" preload="preload" class="w-50 my-auto">
        <source src="{{video.video.url}}" type="video/mp4">
        </source>
    </video><br>
    <h1 class="card-title">{{video.name}}</h1>
    <h3 class="card-text">{{video.discription}}</h3>
    <a href="{% url 'subscription:home' %}" class="btn btn-primary">Go Back</a>
</body>

</html>